In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing

In [ ]:
housing = fetch_california_housing()
X = housing.data
y = housing.target

In [ ]:
print(X.shape)
print(y.shape)

(20640, 8)
(20640,)

In [ ]:
print(housing.feature_names)

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

In [ ]:
import pandas as pd
df = pd.DataFrame(X, columns=housing.feature_names)
df['target'] = y
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [ ]:
regr = LinearRegression()
model = regr.fit(X, y)

In [ ]:
model.intercept_

np.float64(-36.94192020718441)

In [ ]:
model.coef_

array([ 4.36693293e-01,  9.43577803e-03, -1.07322041e-01,  6.45065694e-01,
       -3.97638942e-06, -3.78654265e-03, -4.21314378e-01, -4.34513755e-01])

In [ ]:
cdf = pd.DataFrame(model.coef_, index=housing.feature_names, columns=['coef'])
cdf

                coef
MedInc      0.436693
HouseAge    0.009436
AveRooms   -0.107322
AveBedrms   0.645066
Population -0.000004
AveOccup   -0.003787
Latitude   -0.421314
Longitude  -0.434514

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

Coeffience

In [ ]:
model.coef_

array([ 4.48674910e-01,  9.72425752e-03, -1.23323343e-01,  7.83144907e-01,
       -2.02962058e-06, -3.52631849e-03, -4.19792487e-01, -4.33708065e-01])

Predict

In [ ]:
y_pred = model.predict(X_test)

MSE and R^2

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'MSE: {mse:.4f}')
print(f'R2: {r2:.4f}')

MSE: 0.5559
R2: 0.5758

Ridge Regression

In [ ]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha=1000)
ridge.fit(X_train, y_train)
y_pred_ridge = ridge.predict(X_test)
mse_ridge = mean_squared_error(y_test, y_pred_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)
print(f'MSE Ridge: {mse_ridge:.4f}')
print(f'R2 Ridge: {r2_ridge:.4f}')

MSE Ridge: 0.5461
R2 Ridge: 0.5833

Ridge Coefficience

In [ ]:
ridge.coef_

array([ 4.00508705e-01,  1.10993594e-02, -3.02437173e-02,  2.41663687e-01,
        2.15610668e-06, -3.48144901e-03, -3.67788890e-01, -3.71818461e-01])

In [ ]:
ridge.intercept_

np.float64(-31.246552273973343)

Lasso Regression

In [ ]:
from sklearn.linear_model import Lasso
import numpy as np
lasso = Lasso(alpha=0.07)
lasso.fit(X_train, y_train)
y_pred_lasso = lasso.predict(X_test)
mse_lasso = mean_squared_error(y_test, y_pred_lasso)
r2_lasso = r2_score(y_test, y_pred_lasso)
print(f'MSE Lasso: {mse_lasso:.4f}')
print(f'R2 Lasso: {r2_lasso:.4f}')
print(f'Number of features used: {np.sum(lasso.coef_ != 0)}')

MSE Lasso: 0.5803
R2 Lasso: 0.5571
Number of features used: 6

Lasso Coefficience

In [ ]:
lasso.coef_

array([ 3.89350946e-01,  1.34214761e-02,  0.00000000e+00,  0.00000000e+00,
        9.65603459e-06, -3.18873963e-03, -2.12305536e-01, -2.04052239e-01])

In [ ]:
lasso.intercept_

np.float64(-16.660688473856236)